
export const AlimentoModel = {
    id_alimento: null,
    codigo: null,
    nombre: null,
    id_grupo: null,
    energia_kcal: null,
    energia_kj: null,
    agua_g: null,
    proteinas_totales_g: null,
    proteinas_vegetales_g: null,
    proteinas_animal: null,
    grasa_total_g: null,
    carbohidratos_disponibles_g: null,
    fibra_dietaria_g: null,
    cenizas_g: null,
    calcio_mg: null,
    fosforo_mg: null,
    zinc_mg: null,
    hierro_mg: null,
    caroteno_equivalentes_totales_ug: null,
    vitaminaA_equivalentes_totales_ug: null,
    tiamina_mg: null,
    riboflavina_mg: null,
    niacina_mg: null,
    vitaminaC_mg: null,
    acido_folico_ug: null,
    sodio_mg: null,
    potasio_mg: null
};
